version: '3.7'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.4.3
    command:
      - /usr/local/bin/etcd
      - --listen-client-urls
      - http://0.0.0.0:2379
      - --advertise-client-urls
      - http://etcd:2379
    networks:
      - mynetwork

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
    networks:
      - mynetwork

  hellorpc:
    build:
      context: .
      dockerfile: Dockerfile.hellorpc
    depends_on:
      - etcd
      - jaeger
    ports:
      - 8888:8888
    networks:
      - mynetwork

  likerpc:
    build:
      context: .
      dockerfile: Dockerfile.likerpc
    depends_on:
      - etcd
      - jaeger
    ports:
      - 9000:9000
    networks:
      - mynetwork

  unlikerpc:
    build:
      context: .
      dockerfile: Dockerfile.unlikerpc
    depends_on:
      - etcd
      - jaeger
    ports:
      - 8000:8000
    networks:
      - mynetwork

  commentrpc:
    build:
      context: .
      dockerfile: Dockerfile.commentrpc
    depends_on:
      - etcd
      - jaeger
    ports:
      - 8380:8380
    networks:
      - mynetwork

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - hellorpc
      - likerpc
      - unlikerpc
      - commentrpc
      - jaeger
    ports:
      - 8080:8080
    networks:
      - mynetwork

networks:
  mynetwork:
