version: '3.7'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.4.3
    command:
      - /usr/local/bin/etcd
      - --listen-client-urls
      - http://0.0.0.0:2379
      - --advertise-client-urls
      - http://etcd:2379
    networks:
      - mynetwork

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    depends_on:
      - etcd
    ports:
      - 8888:8888
    networks:
      - mynetwork

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    ports:
      - 8080:8080
    networks:
      - mynetwork

networks:
  mynetwork:
