// Code generated by hertz generator.

package api

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	api "github.com/shamesjen/orbital5/biz/model/api"
	"github.com/shamesjen/orbital5/pkg/constants"
)

// Comment .
// @router /comment [POST]
func Comment(ctx context.Context, c *app.RequestContext) {
	var IDLPATH string = "idl/comment.thrift"
	var jsonData map[string]interface{}
	var service = "comment"

	//return data in bytes
	response := c.GetRawData()

	err := json.Unmarshal(response, &jsonData)

	if err != nil {
		fmt.Println("Error", err)
		c.String(consts.StatusBadRequest, "bad post request")
		return
	}

	jsonData["data"] = constants.CurrentVideoID

	fmt.Println(jsonData)

	responseFromRPC, err := makeThriftCall(IDLPATH, service, jsonData, ctx)

	if err != nil {
		fmt.Println(err)
		c.String(consts.StatusBadRequest, "error in thrift call ")
		return
	}

	fmt.Println("Post request successful")

	c.JSON(consts.StatusOK, responseFromRPC)
}

// Edit .
// @router /edit [PUT]
func Edit(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.CommentRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.Response)

	c.JSON(consts.StatusOK, resp)
}
